environment:
  matrix:
    - nodejs_version: 14
    - nodejs_version: 12
    - nodejs_version: 10

matrix:
  fast_finish: true

build: off

version: '{build}'

shallow_clone: true

clone_depth: 1

install:
  - ps: Install-Product node $env:nodejs_version x64
  - set CI=true
  - npm install -g npm@latest
  - set PATH=%APPDATA%\npm;%PATH%
  - npm install --loglevel=warn
  - choco install make
  - make test

test_script:
  - node --version
  - npm --version
  - npm run test
